-- Databricks notebook source
-- MAGIC %python
-- MAGIC # Set the current database
-- MAGIC spark.sql("USE adventure")
-- MAGIC
-- MAGIC # Get the list of tables in the database
-- MAGIC tables = spark.catalog.listTables()
-- MAGIC
-- MAGIC sql_script = "CREATE DATABASE IF NOT EXISTS adventure;\n"
-- MAGIC sql_script += "USE adventure;\n"
-- MAGIC
-- MAGIC # Generate T-SQL scripts for each table and insert data
-- MAGIC for table in tables:
-- MAGIC     table_name = table.name
-- MAGIC
-- MAGIC     # Get the schema of the table
-- MAGIC     schema = spark.table(table_name).schema
-- MAGIC
-- MAGIC     # Generate the CREATE TABLE statement
-- MAGIC     create_table_sql = f"CREATE TABLE IF NOT EXISTS {table_name} (\n"
-- MAGIC     for field in schema.fields:
-- MAGIC         column_name = field.name
-- MAGIC         column_type = field.dataType.simpleString()
-- MAGIC         create_table_sql += f"  {column_name} {column_type},\n"
-- MAGIC     create_table_sql = create_table_sql.rstrip(",\n") + "\n);\n"
-- MAGIC
-- MAGIC     # Generate the INSERT INTO statements
-- MAGIC     insert_sql = f"INSERT INTO {table_name} VALUES\n"
-- MAGIC     data = spark.table(table_name).collect()
-- MAGIC     for row in data:
-- MAGIC         values = [f"'{str(row[column_name])}'" for column_name in schema.fieldNames()]
-- MAGIC         insert_sql += f"  ({', '.join(values)}),\n"
-- MAGIC     insert_sql = insert_sql.rstrip(",\n") + ";\n"
-- MAGIC
-- MAGIC     sql_script += create_table_sql
-- MAGIC     sql_script += insert_sql
-- MAGIC     
-- MAGIC    # Write the T-SQL scripts to a file
-- MAGIC with open("adventure_script.sql", "w") as file:
-- MAGIC     file.write(sql_script)
-- MAGIC
-- MAGIC

-- COMMAND ----------


